### PR TITLE
add support for arm64

### PR DESCRIPTION
**Pull request by issamsaid**
- add an initial support for arm64
- add a reader for arch specific vars
- add a pattern for versions

### CODE REVIEW

**Comment by issamsaid** [comment]
@andrewhowdencom @freemanjp any thoughts on this?

**Comment by freemanjp** [comment]
@issamsaid sorry for the late reply, I've been focused on a delivery deadline for work. I need you to accept the contributor agreement https://cla-assistant.io/gantsign/ansible-role-golang?pullRequest=144 before I can merge your change.

**Comment by issamsaid** [comment]
@freemanjp I signed the CLA multiple times (You have signed the CLA for gantsign/ansible-role-golang) not sure why it says pending

**Comment by freemanjp** [comment]
@issamsaid the email address you used for the commits isn't associated with your GitHub account, you need to follow the instructions here:  https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by issamsaid** [comment]
@freemanjp I really don't see any of the symptoms discussed about in the link you sent.

**Comment by freemanjp** [comment]
@issamsaid, when I go to the commit tab and click on the author for one of the commits now it takes me to your account, the other day it didn't because the email address for the author of the commit wasn't associated with your GitHub account. I don't know what has changed, but the commits are now associated with your GitHub account, so you should be able to sign the CLA now.

**Comment by freemanjp** [comment]
@issamsaid I clicked recheck on the CLA assistant and it appears to be happy now.

**Comment by freemanjp** [comment]
Sorry, but I'm going to hold off merging this until I've had a go at adding a [Molecule](https://molecule.readthedocs.io/en/latest/) test for arm64. It should get merged sometime this weekend.

**Comment by freemanjp** [comment]
@issamsaid thanks for your pull request, you can find your enhancement in the [2.4.0](https://github.com/gantsign/ansible-role-golang/releases/tag/2.4.0) release of this role.

**Pull request merged**
